live_config_reload = true
import = [
  "~/.config/alacritty/themes/themes/afterglow.toml"
]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A", "-s", "main"]

[window]
decorations = "None"
padding = { x = 5, y = 0 }
dynamic_padding = true
startup_mode = "Maximized"

[font]
# normal = { family = "Intel One Mono", style = "Regular" }
normal = { family = "IntoneMono Nerd Font", style = "Regular" }
size = 20
offset = { x = 0, y = 5 }

