live_config_reload = true
import = [
  # "~/.config/alacritty/themes/themes/afterglow.toml",
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
  "~/.dotfiles/etc/alacritty/themes/tokyonight_moon.toml",
]

[shell]
# program = "/opt/homebrew/bin/zellij"
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A", "-s", "🤓"]

[window]
decorations = "None"
padding = { x = 5, y = 0 }
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
# normal = { family = "Intel One Mono", style = "Regular" }
normal = { family = "IntoneMono Nerd Font", style = "Regular" }
size = 20
offset = { x = 0, y = 5 }
