[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
  "~/.config/alacritty/shared.toml",
  "~/.config/alacritty/darwin.toml",
  "~/.config/alacritty/linux.toml",
]
