[general]
live_config_reload = true
import = [
  # "~/.config/alacritty/themes/themes/afterglow.toml",
  # "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
  # "~/.dotfiles/etc/alacritty/themes/tokyonight_moon.toml",
  "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml",
]

[terminal.shell]
# program = "/opt/homebrew/bin/zellij"
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A", "-s", "work"]

[window]
decorations = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "On"

[bell]
animation = "EaseOutSine"
color = "#b59b9c"
duration = 300

[font]
# normal = { family = "Intel One Mono", style = "Regular" }
normal = { family = "IntoneMono Nerd Font", style = "Regular" }
size = 20
offset = { x = 0, y = 5 }
