# Used by the *.desktop apps
[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
  "~/.config/alacritty/shared.toml",
]

[window]
padding.x = 30
padding.y = 30
