live_config_reload = true

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A", "-s", "work"]

[window]
decorations = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true
startup_mode = "Maximized"

[font]
normal = { family = "Intel One Mono", style = "Regular" }
size = 19
offset = { x = 0, y = 5 }

