tap 'homebrew/core'
tap 'homebrew/services'
tap 'thoughtbot/formulae'
brew 'macvim'
brew 'ripgrep'
brew 'tmux'
brew 'ctags'
brew 'coreutils'
brew 'tree'
brew 'autojump'
brew 'hub'
brew 'bash'
brew 'bash-completion'
brew 'rcm'
brew 'fzf'
brew 'git'
brew 'ccat'
brew 'rbenv'
brew 'nodenv'

tap 'homebrew/cask'
cask_args appdir: '/Applications'
cask 'alfred'
cask 'iterm2'
cask '1password'
cask 'divvy'
cask 'dash'
cask 'keybase'
cask 'docker'
cask 'visual-studio-code'

tap 'homebrew/cask-fonts'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-source-code-pro'
cask 'font-fira-code'
cask 'font-fira-mono'
