tap 'homebrew/core'
tap 'homebrew/services'
tap 'heroku/brew'
tap 'thoughtbot/formulae'
tap 'samandmoore/git-up', 'https://github.com/samandmoore/git-up'
brew 'autojump'
brew 'bash'
brew 'bash-completion'
brew 'ccat'
brew 'comby'
brew 'coreutils'
brew 'ctags'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-up'
brew 'neovim'
brew 'mise'
brew 'rcm'
brew 'ripgrep'
brew 'tmux'
brew 'tpm'
brew 'tree'

# mobile dev things
tap 'robotsandpencils/made'
brew 'xcodes'

tap 'homebrew/cask'
cask_args appdir: '/Applications'
cask '1password'
cask 'alacritty'
cask 'arc'
cask 'licecap'
cask 'raycast'
cask 'visual-studio-code'
cask 'whatsapp'

tap 'homebrew/cask-fonts'
cask 'font-fira-code'
cask 'font-fira-mono'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-jetbrains-mono'
cask 'font-source-code-pro'
cask 'font-intel-one-mono'
