[tools]
"cargo:https://github.com/samandmoore/git-up" = "tag:v0.2.0"
"cargo:presenterm" = "latest"
deno = "latest"
flutter = "latest"
go = "latest"
java = "24"
kotlin = "latest"
node = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
