#!/bin/bash
set -euxo pipefail

function setup_dotfiles() {
  env RCRC=rcrc rcup -fv
}

function setup_homebrew() {
  if [ ! type brew 2>/dev/null ]; then
    echo 'installing brew'
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  if [ -f "$HOME/.Brewfile" ]; then
    brew update
    brew bundle --global
  fi
}

function setup_divvy() {
  if [ ! -f "$HOME/.divvy" ]; then
    open -a safari $(cat etc/divvy/preferences.txt)
    echo "installed divvy preferences" > "$HOME/.divvy"
  fi
}

function setup_vim() {
  if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
    echo 'installing vim-plug for vim magic'
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim +PlugInstall +qall
  fi
}

cd "$(dirname "$0")/.." || exit

setup_homebrew
setup_divvy
setup_dotfiles
setup_vim
