#!/bin/bash
set -euo pipefail

HERE=$(dirname "$0")
OS=$(uname -s | tr '[:upper:]' '[:lower:]')
DOTFILES=~/.dotfiles

function setup_dotfiles() {
  echo 'Setting up dotfiles'
  source "$DOTFILES/bin/rcs"
}

function setup_tools() {
  echo 'Installing tools'
  mise install --install-missing
}

function setup_terminal() {
  if [ ! -d ~/.tmux/plugins/tpm ]; then
    echo 'Installing tmux tools'
    mkdir -p ~/.tmux/plugins/tpm
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    tmux start-server
    tmux new-session -d
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
  fi
}

function setup_os() {
  if [[ $OS = 'linux' ]]; then
    echo 'Linux detected'
    source "$HERE/setup_linux"
  elif [[ $OS = 'darwin' ]]; then
    echo 'macOS detected'
    source "$HERE/setup_macos"
  else
    echo "Unsupported OS: '$OS'"
    exit 1
  fi
}

cd "$HERE/.." || exit

setup_os
setup_dotfiles
setup_tools
setup_terminal
