#!/bin/bash
set -euxo pipefail

DOTFILES=~/.dotfiles

function setup_shell() {
  chsh -s /bin/bash
}

function setup_shell_after_homebrew() {
  if grep -q '/opt/homebrew/bin/bash' /etc/shells; then
    echo '/opt/homebrew/bin/bash' | sudo tee -a /etc/shells
  fi
  chsh -s /opt/homebrew/bin/bash
}

function setup_homebrew() {
  if ! type brew 2>/dev/null; then
    echo 'Installing brew'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  if [ -f ~/.Brewfile ]; then
    echo 'Installing brew dependencies'
    brew update
    brew bundle --global
  elif [ -f "$DOTFILES/Brewfile" ]; then
    echo 'Installing brew dependencies'
    # on first run, rcup hasn't run yet, so
    # let's brew bundle from a special location
    brew update
    brew bundle --file="$DOTFILES/Brewfile" || true
  fi
}

function setup_tools() {
  echo 'Installing tools'
  mise install --install-missing
}

function setup_terminal() {
  if [ ! -d ~/.config/alacritty/themes ]; then
    echo 'Installing alacritty tools'
    mkdir -p ~/.config/alacritty/themes
    git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
  fi

  if [ ! -d ~/.tmux/plugins/tpm ]; then
    echo 'Installing tmux tools'
    mkdir -p ~/.tmux/plugins/tpm
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    tmux start-server
    tmux new-session -d
    ~/.tmux/plugins/tpm/scripts/install_plugins.sh
  fi
}

function setup_dotfiles() {
  echo 'Setting up dotfiles'
  source "$DOTFILES/bin/rcs"
}

cd "$(dirname "$0")/.." || exit

setup_shell
setup_homebrew
setup_shell_after_homebrew
setup_dotfiles
setup_tools
setup_terminal
