close_when_open = true
theme = "custom"
theme_base = []
theme_location = ["~/.config/walker/themes/"]
hotreload_theme = true
timeout = 0
force_keyboard_focus = true

[keys]
next = ["ctrl j", "ctrl n", "down"]
prev = ["ctrl k", "ctrl p", "up"]

[keys.ai]
run_last_response = ["ctrl e"]

[list]
max_entries = 200

[search]
placeholder = " Search..."

[builtins.hyprland_keybinds]
path = "~/.config/hypr/hyprland.conf"
hidden = true

[builtins.applications]
launch_prefix = "uwsm app -- "
placeholder = " Search..."
prioritize_new = true
context_aware = true
show_sub_when_single = false
history = false
icon = ""
hidden = true

[builtins.applications.actions]
enabled = false
hide_category = true

[builtins.bookmarks]
hidden = true

[[builtins.bookmarks.entries]]
label = "Walker"
url = "https://github.com/abenz1267/walker"
keywords = ["walker", "github"]

[[builtins.bookmarks.entries]]
label = "Dotfiles - Github"
url = "https://github.com/samandmoore/dotfiles"
keywords = ["dotfiles", "github"]

[builtins.calc]
name = "Calculator"
icon = ""
min_chars = 3       # Min chars to calculate. 3 allows "3+3"
prefix = "="

[builtins.windows]
switcher_only = true
hidden = true

[builtins.clipboard]
hidden = true

[builtins.commands]
hidden = true

[builtins.custom_commands]
hidden = true

[builtins.emojis]
name = "Emojis"
icon = ""
prefix = ":"

[builtins.symbols]
after_copy = ""
hidden = true

[builtins.finder]
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
icon = "file"
name = "Finder"
preview_images = true
hidden = false
prefix = "."

[builtins.runner]
shell_config = ""    # Path to shell to parse for aliases
switcher_only = true
hidden = true

[builtins.ssh]
hidden = true

[builtins.websearch]
switcher_only = true
hidden = true

[[builtins.websearch.entries]]
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"
switcher_only = true

[[builtins.websearch.entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[builtins.translation]
hidden = true
