#!/bin/sh
set -e
mkdir .git/tags_lock 2>/dev/null || exit 0
trap 'rm -rf .git/tags_lock; rm .git/tags.$$' EXIT
PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql,html
mv -f "$dir/$$.tags" "$dir/tags"
rm -rf .git/tags_lock
