[alias.java.versions]
"17.0.8" = "temurin-17.0.8+7"
"21" = "temurin-21.0.6+7.0.LTS"

[tools]
deno = "2.0.3"
flutter = "3.19.3"
go = "1.23.1"
java = "21"
node = "18.16.0"
python = "3.12.1"
ruby = "3.2.3"
rust = "latest"
