[alias.java.versions]
"17.0.8" = "temurin-17.0.8+7"
"21" = "temurin-21.0.6+7.0.LTS"

[tools]
"cargo:https://github.com/samandmoore/git-up" = "tag:v0.2.0"
deno = "latest"
flutter = "3.19.3"
go = "latest"
java = "21"
node = "latest"
python = "3.12.1"
ruby = "latest"
rust = "latest"
